from typing import Any

def quat_rotate(q: Any, v: Any) -> Any: ...
def quat_rotate_inverse(q: Any, v: Any) -> Any: ...
def quat_mul(a: Any, b: Any) -> Any: ...
def quat_conjugate(q: Any) -> Any: ...
def quat_apply(a: Any, b: Any) -> Any: ...
def normalize(x: Any) -> Any: ...
def get_euler_xyz(q: Any) -> Any: ...
def torch_rand_float(low: Any, high: Any, shape: Any, device: Any) -> Any: ...
def to_torch(x: Any, device: Any, requires_grad: bool = ...) -> Any: ...
def get_axis_params(value: float, axis: int) -> Any: ...
